### ISSUE TITLE
Data Collection

### ISSUE THREAD

**Issue by Sahandfer** [nbertagnolli/counsel-chat#8]
Hello,
I recently came across your article and found it to be an amazing piece. I had some questions about copyright issues regarding the usage of this data. I was reading the TOS on counselchat and they strictly prohibit crawling data from their website. Therefore, I wanted to ask if you had any problems with copyright during this project. I also wanted to ask about whether it was possible to collect more data from this website, given that your data was collected last year, and if so, who I can contact.

Thank you!

**Comment by nbertagnolli** [comment]
I'm glad that you liked it!  I spoke with Phillip and Eric about this article and they gave me permission to publish it.  I'm no lawyer but I think you're free to use this data.  I'd just email Eric or Phillip and describe what you want to do with it : ).

**Comment by Sahandfer** [comment]
Will do! Thanks so much for the help, I appreciate it.

**Comment by Sahandfer** [comment]
Hello again,
I emailed counselchat support as well as Eric but I haven't received any replies so far. Do you have any suggestions about ways to contact them other than by email? Thank you in advance.
